# Generated by Django 3.2.11 on 2022-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20210512_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesauruskeywordlabel',
            name='lang',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thesauruslabel',
            name='lang',
            field=models.CharField(max_length=10),
        ),
    ]
