# Generated by Django 2.2.24 on 2022-01-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20211117_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesauruskeywordlabel',
            name='lang',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thesauruslabel',
            name='lang',
            field=models.CharField(max_length=10),
        ),
    ]
